---
- name: Install z Chocolatey
  hosts: "{{ seznam_stanic }}"
  tasks: 
   - name: Install z Chocolatey
     win_chocolatey: 
      name: "{{ aplikace1 }}"
   - name: Install z Chocolatey
     win_chocolatey: 
      name: "{{ aplikace2 }}"
   - name: Install z Chocolatey
     win_chocolatey: 
      name: "{{ aplikace3 }}"
