---
- name: Install z Chocolatey
  hosts: "{{ seznam_stanic }}"
  tasks: 
   - name: Install z Chocolatey
     win_chocolatey: 
      name: "{{ apka }}"
      state: "{{ stav }}"
     ignore_errors: yes
     
