---
- name: Install chocolatey pomocí powershellu
  hosts: "{{ seznam_stanic }}"
  tasks: 
  - name: Instalace
    win_shell: | 
     Set-ExecutionPolicy Bypass -Scope Process -Force; `
      iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
