---
- name: Install chocolatey pomocí powershellu
  hosts: "{{ seznam_stanic }}"
  tasks: 
  - name: Instalace
    win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force; iwr https://chocolatey.org/install.ps1 -UseBasicParsing | iex
